#+title: Functional Differential Geometry
#+PROPERTY: header-args :eval no-export
#+LATEX_HEADER: \usepackage[hang,flushmargin]{footmisc}
#+LATEX_HEADER: \setlength{\footnotesep}{\baselineskip}
# required for epub:
# #+OPTIONS: tex:dvipng

#+Author: Gerald Jay Sussman and Jack Wisdom
#+Email: gjs@mit.edu

#+begin_quote
The author has spared himself no pains in his endeavour to present the main
ideas in the simplest and most intelligible form, and on the whole, in the
sequence and connection in which they actually originated. In the interest of
clearness, it appeared to me inevitable that I should repeat myself frequently,
without paying the slightest attention to the elegance of the presentation. I
adhered scrupulously to the precept of that brilliant theoretical physicist L.
Boltzmann, according to whom matters of elegance ought be left to the tailor and
to the cobbler.

Albert Einstein, in Relativity, the Special and General Theory, (1961), p. v
#+end_quote

#+include: preface.org :minlevel 1
#+include: prologue.org :minlevel 1
#+include: chapter001.org :minlevel 1

# TODO see here for more book examples: https://github.com/jkitchin/pycse
# TODO we are having some trouble with footnotes. https://www.ctan.org/pkg/bigfoot
