#+title: Chapter 4: Introduction
#+STARTUP: noindent


A vector field may be written as a linear combination of basis vector fields. If
=n= is the dimension, then any set of =n= linearly independent vector fields may
be used as a basis. The coordinate basis $\mathsf{X}$ is an example of a basis.[fn:1]
We will see later that not every basis is a coordinate basis: in order to be a
coordinate basis, there must be a coordinate system such that each basis element
is the directional derivative operator in a corresponding coordinate direction.

Let $\mathsf{e}$ be a tuple of basis vector fields, such as the coordinate basis
$\mathsf{X}$. The general vector field $\mathsf{v}$ applied to an arbitrary
manifold function $\mathsf{f}$ can be expressed as a linear combination

\begin{equation}
\mathsf{v}(\mathsf{f})(\mathsf{m}) = \mathsf{e}(\mathsf{f})(\mathsf{m}) \
\mathsf{b}(\mathsf{m}) = \
\sum_i \mathsf{e}_i(\mathsf{f})(\mathsf{m})\mathsf{b}^i(\mathsf{m}),
\end{equation}

where $\mathsf{b}$ is a tuple-valued coefficient function on the manifold. When
expressed in a coordinate basis, the coefficients that specify the direction of
the vector are naturally expressed as functions $b^i$ of the coordinates of the
manifold point. Here, the coefficient function $\mathsf{b}$ is more naturally
expressed as a tuple-valued function on the manifold. If $b$ is the coefficient
function expressed as a function of coordinates, then $\mathsf{b} = b \circ
\chi$ is the coefficient function as a function on the manifold.

The coordinate-basis forms have a simple definition in terms of the
coordinate-basis vectors and the coordinates (equation 3.40). With this choice,
the dual property, equation (3.41), holds without further fuss. More generally,
we can define a basis of one-forms $\tilde{\mathsf{e}}$ that is dual to
$\mathsf{e}$ in that the property

\begin{equation}
\tilde{\mathsf{e}}^i(\mathsf{e}_j)(\mathsf{m}) = \delta^i_j
\end{equation}

is satisfied, analogous to property (3.41). Figure 4.1 illustrates the duality
of basis fields.

TODO add Figure 4.1 with this caption: Let arrows $\mathsf{e_0}$ and
$\mathsf{e_q}$ depict the vectors of a basis vector field at a particular point.
Then the foliations shown by the parallel lines depict the dual basis one-form
fields at that point. The dotted lines represent the field
$\tilde{\mathsf{e}}^0$ and the dashed lines represent the field
$\tilde{\mathsf{e}}^1$. The spacings of the lines are 1/3 unit. That the vectors
pierce three of the lines representing their duals and do not pierce any of the
lines representing the other basis elements is one way to see the relationship
$\tilde{\mathsf{e}}^i(\mathsf{e}_j) = \delta^i_j.$

To solve for the dual basis $\tilde{\mathsf{e}}$ given the basis $\mathsf{e}$,
we express the basis vectors $\mathsf{e}$ in terms of a coordinate basis[fn:2]

TODO continue from page 42!

* Footnotes
[fn:2] We write the vector components on the right and the tuple of basis
vectors on the left because if we think of the basis vectors as organized as a
row and the components as organized as a column then the formula is just a
matrix multiplication.

[fn:1] We cannot say if the basis vectors are orthogonal or normalized until we
introduce a metric.
