#+title: Chapter 3: Vector Fields and One-Form Fields
#+STARTUP: noindent

We want a way to think about how a function varies on a mani- fold. Suppose we
have some complex linkage, such as a multiple pendulum. The potential energy is
an important function on the multi-dimensional configuration manifold of the
linkage. To un- derstand the dynamics of the linkage we need to know how the
potential energy changes as the configuration changes. The change in potential
energy for a step of a certain size in a particular di- rection in the
configuration space is a real physical quantity; it does not depend on how we
measure the direction or the step size. What exactly this means is to be
determined: What is a step size? What is a direction? We cannot subtract two
configurations to determine the distance between them. It is our job here to
make sense of this idea.

So we would like something like a derivative, but there are prob- lems. Since we
cannot subtract two manifold points, we cannot take the derivative of a manifold
function in the way described in elementary calculus. But we can take the
derivative of a co- ordinate representation of a manifold function, because it
takes real-number coordinates as its arguments. This is a start, but it is not
independent of coordinate system. Let's see what we can build out of this.

** Vector Fields

   In multiple dimensions the derivative of a function is the multiplier for the
   best linear approximation of the function at each argument point:[fn:1]

\begin{equation}
f(x + \Delta x) \approx f(x) + (Df(x)) \Delta x
\end{equation}

   The derivative $Df(x)$ is independent of $\Delta x$. Although the derivative
   depends on the coordinates, the product $(Df(x)) \Delta x$ is invariant under
   change of coordinates in the following sense. Let $\phi = \chi \circ
   \chi^{\prime -1}$ be a coordinate transformation, and $x = \phi(y)$. Then
   $\Delta x = D\phi(y)\Delta y$ is the linear approximation to the change in
   $x$ when $y$ changes by $\Delta y$. If $f$ and $g$ are the representations of
   a manifold function in the two coordinate systems, $g(y) = f(\phi(y)) =
   f(x)$, then the linear approximations to the increments in $f$ and $g$ are
   equal:

\begin{equation}
\end{equation}

* Footnotes

[fn:1] In multiple dimensions the derivative $Df(x)$ is a down tuple structure
of the partial derivatives and the increment $\Delta x$ is an up tuple
structure, so the indicated product is to be interpreted as a contraction. (See
equation B.8.)
